[package]
name = "mjrust"
version = "0.1.0"
authors = ["likewater"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# 添加第一个依赖的库
mjlib = { path = "mjlib/" }

# 从 https://crates.io/  引入crate
random = "0.12.2"