[package]
name = "mjalgorithm"
version = "0.1.0"
authors = ["likewater"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# A collection of numeric types and traits for Rust 
num = "0.2.1"